function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(14)=params(8);
    ys_(10)=0.003;
    k_over_gh=((ys_(14)-1+params(2))/params(3))^(1/(params(3)-1));
    ys_(4)=((1-params(3))*k_over_gh^params(3)/params(6))^(1/(params(5)-1));
    ys_(2)=k_over_gh*ys_(4);
    ys_(7)=params(2)*ys_(2);
    ys_(6)=ys_(2)^params(3)*ys_(4)^(1-params(3));
    ys_(8)=ys_(10)*ys_(6);
    ys_(5)=(-ys_(8))/(1/ys_(14)-1);
    ys_(1)=ys_(6)+(1/ys_(14)-1)*ys_(5)-ys_(7);
    ys_(9)=(ys_(1)-params(6)/params(5)*ys_(4)^params(5))^(-params(1));
    ys_(3)=1;
    ys_(12)=1;
    ys_(13)=1;
    ys_(11)=1;
    ys_(8)=exp(ys_(8));
    ys_(10)=exp(ys_(10));
    % Auxiliary equations
end
